image: ubuntu

# stack: go 1.12

version: '{build}'

cache:
- go1.14.deb

install:
- 'if [[ $APPVEYOR_REPO_TAG == "true" ]]; then appveyor UpdateBuild -Version "$(git describe --tags --always)"; else appveyor UpdateBuild -Version "$(git rev-parse --short HEAD)"; fi'
- 'wget --no-clobber -O go1.14.deb https://deb.geek1011.net/pool/main/g/go/go_1.14-godeb1_amd64.deb || true'
- sudo dpkg -i go1.14.deb
- go mod download

build_script:
- ./build.sh
- LOG="$(git log --pretty='- %h %s' $(git describe --tags --abbrev=0)..HEAD | awk '{printf "%s\\n", $0}')"
- export "RELEASE_NOTES=$LOG"

test: off

artifacts:
- path: build/*

deploy:
  release: $(APPVEYOR_BUILD_VERSION)
  description: $(RELEASE_NOTES)
  provider: GitHub
  auth_token:
    secure: oMHoA3qAfCcz3PsfBJmce+fKcSOtUF1cTC3RUj1qKT4J4BjbkOcawazIrXR4F1eb
  artifact: /.+/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
