kind: pipeline
name: default

steps:
- name: tags
  image: golang:1.14-stretch
  commands:
  - git fetch --tags

- name: build-tools
  image: golang:1.14-stretch
  commands:
  - go mod download
  - go build ./tools/dictlookup
  - go build ./tools/dictparse
  - go build ./tools/dictverify

- name: build-server
  image: golang:1.14-stretch
  commands:
  - go build .
  depends_on:
  - tags

- name: test
  image: golang:1.14-stretch
  commands:
  - go test -v ./...

- name: dictionary-parse
  image: golang:1.14-stretch
  commands:
  - ./dictparse ./data/dictionary.txt ./dict
  depends_on:
  - build-tools

- name: dictionary-test
  image: golang:1.14-stretch
  commands:
  - ./dictverify ./dict
  depends_on:
  - build-tools
  - dictionary-parse

- name: dictionary-download-v5
  image: golang:1.14-stretch
  commands:
  - wget -O./dict.v5 https://github.com/pgaskin/dictserver/releases/download/v1.3.1/dict

- name: dictionary-test-v5
  image: golang:1.14-stretch
  commands:
  - ./dictverify ./dict.v5
  depends_on:
  - build-tools
  - dictionary-download-v5

- name: build-cross
  image: golang:1.14-stretch
  commands:
  - mkdir build
  - cp ./dict ./build/
  - GOOS=linux   GOARCH=amd64 go build -o "./build/dictlookup_linux-x64"   -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictlookup"
  - GOOS=linux   GOARCH=amd64 go build -o "./build/dictparse_linux-x64"    -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictparse"
  - GOOS=linux   GOARCH=amd64 go build -o "./build/dictverify_linux-x64"   -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictverify"
  - GOOS=linux   GOARCH=amd64 go build -o "./build/dictserver_linux-x64"   -ldflags "-s -w -X main.version=$(git describe --tags --always)" "."
  - GOOS=linux   GOARCH=arm   go build -o "./build/dictlookup_linux-arm"   -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictlookup"
  - GOOS=linux   GOARCH=arm   go build -o "./build/dictparse_linux-arm"    -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictparse"
  - GOOS=linux   GOARCH=arm   go build -o "./build/dictverify_linux-arm"   -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictverify"
  - GOOS=linux   GOARCH=arm   go build -o "./build/dictserver_linux-arm"   -ldflags "-s -w -X main.version=$(git describe --tags --always)" "."
  - GOOS=windows GOARCH=amd64 go build -o "./build/dictlookup_windows.exe" -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictlookup"
  - GOOS=windows GOARCH=amd64 go build -o "./build/dictparse_windows.exe"  -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictparse"
  - GOOS=windows GOARCH=amd64 go build -o "./build/dictverify_windows.exe" -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictverify"
  - GOOS=windows GOARCH=amd64 go build -o "./build/dictserver_windows.exe" -ldflags "-s -w -X main.version=$(git describe --tags --always)" "."
  - GOOS=darwin  GOARCH=amd64 go build -o "./build/dictlookup_darwin-x64"  -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictlookup"
  - GOOS=darwin  GOARCH=amd64 go build -o "./build/dictparse_darwin-x64"   -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictparse"
  - GOOS=darwin  GOARCH=amd64 go build -o "./build/dictverify_darwin-x64"  -ldflags "-s -w -X main.version=$(git describe --tags --always)" "./tools/dictverify"
  - GOOS=darwin  GOARCH=amd64 go build -o "./build/dictserver_darwin-x64"  -ldflags "-s -w -X main.version=$(git describe --tags --always)" "."
  depends_on:
  - tags
  - dictionary-parse

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: build/*
  when:
    event: tag
  depends_on:
  - dictionary-test
  - dictionary-test-v5
  - build-cross
